version: '3.8'
services: 
  client:
    image: andrewpatrickmiller/robot-photographer:client
    ports:
      - "8080:8080"
    networks:
      - app-photo

  photo-server:
    privileged: true
    image: docker.io/andrewpatrickmiller/robot-photographer:photo-server
    ports:
      - "3000:3000"
    networks:
      - app-photo

networks: 
  app-photo:
    external: 
      name: nat

